export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CREATE_JOB_PENDING = 'CREATE_JOB_PENDING';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_REJECTED = 'CREATE_JOB_REJECTED';
export const FETCH_ALL_JOBS_PENDING = 'FETCH_ALL_JOBS_PENDING';
export const FETCH_ALL_JOBS_SUCCESS = 'FETCH_ALL_JOBS_SUCCESS';
export const FETCH_ALL_JOBS_REJECTED = 'FETCH_ALL_JOBS_REJECTED';